// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyYoBaj19_iFQdZOLB0BVS3tZ3yb28R6M',
    appId: '1:776382900846:web:3ab48f9009c6fb63d3d47f',
    messagingSenderId: '776382900846',
    projectId: 'terzo-kamran',
    authDomain: 'terzo-kamran.firebaseapp.com',
    storageBucket: 'terzo-kamran.firebasestorage.app',
    measurementId: 'G-HX7JTM69YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSV8vEnPa4VolthuJM4UI6kUO_1VXMpQ',
    appId: '1:776382900846:android:9b174f9ebf2e0913d3d47f',
    messagingSenderId: '776382900846',
    projectId: 'terzo-kamran',
    storageBucket: 'terzo-kamran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLd9QlRwAtTjGau7vHsMXlZYPNKC90JY',
    appId: '1:776382900846:ios:9069cc130f6ef673d3d47f',
    messagingSenderId: '776382900846',
    projectId: 'terzo-kamran',
    storageBucket: 'terzo-kamran.firebasestorage.app',
    iosClientId: '776382900846-cihkpfdo262ei5ghslrf8a2pu9icpqus.apps.googleusercontent.com',
    iosBundleId: 'com.example.trezoSavingAiApp',
  );
}
